### ISSUE TITLE
Can't install unhcrshiny package

### ISSUE THREAD

**Issue by bluefoxr** [UNHCR-Guatemala/A2SIT#24]
Hi @Edouard-Legoupil thanks so much for all the changes to incorporate the new CSS but I can't run the app because the unhcrshiny package is not accessible, this has also caused the CMD check to fail. Is the package on GitHub? You can use `usethis::use_dev_package()` to specify the repo in the DESCRIPTION file. Otherwise I can also do that if you tell me where the repo is.
Thanks,
Will

**Comment by Edouard-Legoupil** [comment]
Oups! Sorry - it's here: https://github.com/Edouard-Legoupil/unhcrshiny !

**Comment by bluefoxr** [comment]
Thanks! But also now I see in the unhcrshiny package there is an undeclared package "unchrthemes", which prevents me from installing it...

ERROR: dependency 'unhcrthemes' is not available for package 'unhcrshiny'
* removing 'C:/Users/beckewi/RLib/unhcrshiny'

**Comment by Edouard-Legoupil** [comment]
Hi - Sorry - just cleaned the package - can you try again?

**Comment by bluefoxr** [comment]
Thanks, it works now. Closing the issue.
