### ISSUE TITLE
As dev, I would like to deploy the app on Rstudio connect in order to review it

### ISSUE THREAD

**Issue by Edouard-Legoupil** [UNHCR-Guatemala/A2SIT#3]
The app is expected to run live on http://rstudio.unhcr.org

Currently, when deployed, it provides an error message -

`Preparing to deploy application...DONE
Uploading bundle for application: 156...Error in inferAppPrimaryDoc(appPrimaryDoc = appPrimaryDoc, appFiles = appFiles,  : 
  Application mode static requires at least one document.
Calls: <Anonymous> ... withStatus -> force -> bundleApp -> inferAppPrimaryDoc
Execution halted `

## Client - Validation 

+ [ ] Have a simple application deployment function - maybe based on https://search.r-project.org/CRAN/refmans/rsconnect/html/deployApp.html 

## Dev - Tech

+ [ ] Document the required parameters for Application deployment for the app
+ [ ] Technical validation (tests, check etc.)

**Comment by bluefoxr** [comment]
The app is not yet set up for deployment. Ideally I would like to have access to R Studio Connect so I can test this myself. In any case I will certainly integrate this when possible.

**Comment by Edouard-Legoupil** [comment]
Golem comes with dedicated capacity for deployment on Rstudio connect - https://rdrr.io/cran/golem/man/rstudio_deploy.html  - @bluefoxr  Maybe we can start prototyping directly in Golem ? I can see here examples of how to build a shinydashboardplus  with Golem - https://community.rstudio.com/t/golem-package-and-shinydashboardplus/133231/2
