### ISSUE TITLE
[BUG] f_generate_input_template is broken

### ISSUE THREAD

**Issue by Edouard-Legoupil** [UNHCR-Guatemala/A2SIT#37]
**Describe the bug**

Country template does not work... 

**To Reproduce**
Go to https://rstudio.unhcr.org/A2SIT - then  Data upload - select venezuela - and click on download template 

https://rstudio.unhcr.org/A2SIT/_w_199084a1/session/b945b2f483f93780bcfb4b85f27d5d88/download/id_input-download_country_template?w=199084a1

**Expected behavior**
Should be able to download a country template..  but nothing comes out from the download button

**Note**
R/f_input.R - https://github.com/UNHCR-Guatemala/A2SIT/blob/e927edcbce0e0cc87e34ec0bce66ca4e0fa91120/R/f_input.R#L269  

The related back office function could include unit testing and an example...

**Comment by Edouard-Legoupil** [comment]
FYI - Workaround on the consolde

```
library(A2SIT) 
VEN <- readRDS("inst/geom/VEN.RDS")
f_generate_input_template(df_geom = VEN, 
                                      to_file_name = "dev/text.xlsx",
                                   #   uCode_col = NULL, uName_col = NULL,
                                      with_fake_data = TRUE)
```

**Comment by bluefoxr** [comment]
Hi, this is now fixed. It was related to the addition of the user geometry upload, which significantly complicated the back end processes in the app. Anyway I tested various downloads now and it all seems to work.

**Comment by Edouard-Legoupil** [comment]
thanks!
